from ..core import Dimension

SCALAR_DIMENSION = Dimension()
DIMENSIONLESS_DIMENSION = Dimension()

TIME_DIMENSION = Dimension(time=1)
LENGTH_DIMENSION = Dimension(length=1)
MASS_DIMENSION = Dimension(mass=1)
ANGLE_DIMENSION = Dimension(angle=1)
CURRENT_DIMENSION = Dimension(current=1)
TEMPERATURE_DIMENSION = Dimension(temperature=1)
AMOUNT_OF_SUBSTANCE_DIMENSION = Dimension(amount_of_substance=1)
LUMINOUS_INTENSITY_DIMENSION = Dimension(luminous_intensity=1)
DATA_DIMENSION = Dimension(data=1)

FREQUENCY_DIMENSION = TIME_DIMENSION ** -1

AREA_DIMENSION = LENGTH_DIMENSION ** 2
VOLUME_DIMENSION = LENGTH_DIMENSION ** 3

VELOCITY_DIMENSION = LENGTH_DIMENSION / TIME_DIMENSION
ACCELERATION_DIMENSION = VELOCITY_DIMENSION / TIME_DIMENSION
JERK_DIMENSION = ACCELERATION_DIMENSION / TIME_DIMENSION

SOLID_ANGLE_DIMENSION = ANGLE_DIMENSION ** 2
ANGULAR_VELOCITY_DIMENSION = ANGLE_DIMENSION / TIME_DIMENSION
ANGULAR_ACCELERATION_DIMENSION = ANGULAR_VELOCITY_DIMENSION / TIME_DIMENSION

FORCE_DIMENSION = MASS_DIMENSION * ACCELERATION_DIMENSION
TORQUE_DIMENSION = FORCE_DIMENSION * LENGTH_DIMENSION
ENERGY_DIMENSION = FORCE_DIMENSION * LENGTH_DIMENSION
POWER_DIMENSION = ENERGY_DIMENSION / TIME_DIMENSION
PRESSURE_DIMENSION = FORCE_DIMENSION / LENGTH_DIMENSION ** 2
DENSITY_DIMENSION = MASS_DIMENSION / LENGTH_DIMENSION ** 3
ANGULAR_INERTIA_DIMENSION = MASS_DIMENSION * LENGTH_DIMENSION ** 2

ELECTRIC_POTENTIAL_DIMENSION = POWER_DIMENSION / CURRENT_DIMENSION
ELECTRIC_RESISTANCE_DIMENSION = ELECTRIC_POTENTIAL_DIMENSION / CURRENT_DIMENSION
ELECTRIC_CAPACITANCE_DIMENSION = CURRENT_DIMENSION * TIME_DIMENSION / ELECTRIC_POTENTIAL_DIMENSION
ELECTRIC_INDUCTANCE_DIMENSION = ELECTRIC_POTENTIAL_DIMENSION * TIME_DIMENSION / CURRENT_DIMENSION

MAGNETIC_FLUX_DIMENSION = ELECTRIC_POTENTIAL_DIMENSION * TIME_DIMENSION
MAGNETIC_FLUX_DENSITY_DIMENSION = MAGNETIC_FLUX_DIMENSION / AREA_DIMENSION

LUMINOUS_FLUX_DIMENSION = LUMINOUS_INTENSITY_DIMENSION * SOLID_ANGLE_DIMENSION
ILLUMINANCE_DIMENSION = LUMINOUS_FLUX_DIMENSION / AREA_DIMENSION

CONCENTRATION_DIMENSION = AMOUNT_OF_SUBSTANCE_DIMENSION / LENGTH_DIMENSION ** 3

DATA_TRANSFER_RATE_DIMENSION = DATA_DIMENSION / TIME_DIMENSION